spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_agent
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate   # schema is owned by schema.sql / migrations, not Hibernate
    open-in-view: false
    properties:
      hibernate:
        jdbc:

  sql:
    init:
      mode: never          # we run schema.sql manually / via flyway later, not on every boot

server:
  port: 8080

logging:
  level:
    com.jfl.appointment: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:YnJlYXRoZWNhcmJvbm1lYW50YWN0aW9ubGF0ZXJsaXZpbmdmb3JtbGVhdGhlcmRlc2U=}
    expiration: 3600000
