package com.jfl.appointment.entity;

public enum ConversationState {
    STARTED, COLLECTING_SERVICE, COLLECTING_DOCTOR, COLLECTING_DATE,
    SHOWING_SLOTS, WAITING_FOR_SLOT, COLLECTING_NAME, CONFIRMING, BOOKED, ABANDONED
}
